#inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
    - db/migrate/*  #may be able to remove after merge
    - config/initializers/devise.rb

Lint/HandleExceptions:
  Exclude:
    - bin/rake
    - bin/rails
